apiVersion: v1
data:
  ANTHROPIC_API_KEY: c2stYW50LWFwaTAzLW1ZVHlHUEtqeDlpclFFM0dRdE16aVBiekUzOE5Oa2NKVVZIbVk5ZDNRQXo2bHFCX1lSSFlTVmp0RGhwMDZtbVU1ZnZnSWNDT2h2clRvc3BTcWNrSkZBLXhCdER4QUFBCg==
kind: Secret
metadata:
  name: anthropic-api-key
  namespace: org-giantswarm
type: Opaque
