version: 2.1
orbs:
  architect: giantswarm/architect@6.7.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        registries-data: |-
          public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
        tag-latest-branch: "main"
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            
    - architect/push-to-app-catalog:
        executor: app-build-suite
        context: architect
        name: push-to-default-catalog
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: shoot
        requires:
        - push-to-registries
        persist_chart_archive: true
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
